### ISSUE TITLE
Enigmail: editing draft doesn't cancel send-later as expected

### ISSUE THREAD

**Issue by mcorb** [jikamens/send-later#5] opened 2016-10-19 02:41 UTC
Interaction issue between current Enigmail and send-later:

When you schedule a mail (ordinary, unencrypted) then Edit the draft, send-later is expected to cancel the scheduled time for that mail. It works fine with only send-later enabled.

However, with Enigmail enabled too, editing the scheduled draft causes what appears to be a new, encrypted draft to be created, and unfortunately the original scheduled draft gets sent independently while the user is editing the new copy.

The expected behaviour is that the scheduled time would be cancelled, and Enigmail would respect that I chose not to encrypt the mail.

I'm not familiar with your code, but it looks to my untrained eye like this could be easier to fix on the Enigmail end, or with coordination with their developers.

Thanks so much for the work - it's in use by volunteers at a charity and the enigmail+send-later combo really makes a difference to daily community work

**Comment by jikamens** [comment] 2016-10-19 12:42
Thanks for your report.

Unfortunately, I can't (yet) reproduce this problem.

Here's what I did:
1. Make sure the Enigmail add-on is installed and active.
2. Make sure Enigmail is configured to encrypt draft messages.
3. Compose a new message.
4. Enable Enigmail encryption for the message you are composing.
5. Schedule the message to be sent in 15 minutes.
6. Double-click the scheduled message to edit it.

When I followed these steps, the previously scheduled draft was deleted and replaced with an unscheduled draft, as expected.

Just out of curiosity, is the email account where you're having this problem a Gmail account? Numerous Gmail users have encountered problems where drafts don't get deleted when they should.

**Comment by mcorb** [comment] 2016-10-19 14:41
Hi @jikamens 

I've followed the procedure, now switching my Drafts folder which was previously on IMAP over to Local Folders.

The problem still persists and the original scheduled draft gets sent while I'm editing the double-clicked version. The original fails to get deleted regardless of whether the mail itself is enigmail-encrypted or not. I'm on macOS.

Disabling the enigmail plugin, again, it works - double-clicking prevents the original scheduled mail from getting sent. Can you think of other diagnostics to narrow it down?

**Comment by jikamens** [comment] 2016-10-19 15:27
I'm mostly stumped.

Can you check what versions of Enigmail and Send Later you're using? Perhaps there is a version issue.

Do you have any other non-standard Enigmail settings that you can think of?

What happens when you edit a saved draft that was _not_ scheduled with Send Later and then save the edited draft?

**Comment by mcorb** [comment] 2016-10-20 16:13
Running Enigmail version 1.9.5 (20160820-1403) 
Send Later 6.1

Scheduling a non-scheduled draft works as expected - the scheduled date appears. However this one also doesn't get cancelled during a subsequent edit of the mail.

Some good news: hitting Save immediately after the editor _does_ successfully cancel the scheduled time - so can be used as a workaround if the user is patient, and maybe will give a clue as to what's going wrong

**Comment by jikamens** [comment] 2016-10-20 23:16
I was using Enigmail 1.9.1, but I just tested again with 1.9.5 and still can't reproduce it.

Let me make sure I'm understanding the issue properly....
1. You schedule a message with Send Later.
2. You see the scheduled message as a draft in your Drafts folder, with a scheduled send time shown.
3. You double-click on the message in your Drafts folder to edit it.
4. There are now two copies of the message in your Drafts folder, one with a scheduled send time and one without.
5. When the original scheduled send time arrives, the old copy of the message is sent by Send Later.

Is that correct?

> Scheduling a non-scheduled draft works as expected - the scheduled date appears.

That's not exactly what I asked you:

> What happens when you edit a saved draft that was not scheduled with Send Later and then save the edited draft?

What I am asking you to test is this:
1. Compose a message.
2. Save it as a normal draft and close the composition window.
3. Double-click the draft to edit it.
4. Save it again.

After those steps, do you have two copies of the message or one?

**Comment by mcorb** [comment] 2016-10-21 06:02
Apologies: my statement "what appears to be a new, encrypted draft to be created" in the original report wasn't really accurate.

Double-clicking, and/or hitting Save during editing of a previously saved Draft doesn't create an unwanted second copy - so far so good. There is only ever one copy of the message in Drafts, so there's no problem with duplication in the Drafts folder.

The problem observed is rather that the scheduled time remains set on the previously saved draft copy of the mail, even when you're editing it via double-click.

Hence the old saved draft gets automatically sent while you're editing it if the time was due during the time that you're editing it.

So I have to remember to click Save manually as soon as I start editing for the scheduled time to get removed, otherwise the previously-saved draft gets sent. The expectation would be that double-clicking the draft for editing would do this Save automatically but for some reason that's not happening.

**Comment by jikamens** [comment] 2016-10-21 16:00
When you double-click on the draft to edit it, do you see it briefly disappear from the Drafts folder message list and come back, or does it stay there (This test is better done using the IMAP Drafts folder rather than Local Folders)?

Please try this:
1. Download and install this version of Send Later: http://gofile.me/2J75a/ggD6jnmPx
2. Open Send Later's preferences (click on "Send Later" at the bottom of the main TB window and select "Send Later preferences"), click on the "Advanced" tab and make sure "Console log level" is set to "Warn".
3. Schedule a message to be sent later.
4. Open the Error Console (Tools | Error Console), click the "Clear" button, and leave the window open.
5. Double click on the scheduled message to edit it.
6. Enter "NotifyComposeBodyReady" in the "Filter" box at the bottom of the Error Console.
7. You should see these two messages:
   
   ![error console_004](https://cloud.githubusercontent.com/assets/1598067/19605008/dc38d204-9785-11e6-8482-ed57ffa08df1.png)

Let me know if you do.

Thanks!

**Comment by jikamens** [comment] 2017-08-11 13:15
Closing this issue because I can't reproduce it and the reporter has not responded to requests for more information.

**Closed as completed by jikamens** 2017-08-11 13:15 UTC
